name: PlanetPlugin
version: '1.0'
main: webhead1104.planetplugin.PlanetPlugin
author: Webhead1104
api-version: '1.20'
depend:  [WorldGuard,WorldEdit]
commands:
  planet:
  visit:
  pladmin:
permissions:
  planetplugin.*:
    default: op
    description: A wildcard permission
    children:
      - planetplugin.admin
    planetplugin.admin:
      description: Admin permissions
      default: op